services:
  grid-trader:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    image: grid-trading-bot:latest
    container_name: grid-trader
    restart: unless-stopped
    
    # 环境变量 - 使用 .env 文件
    env_file:
      - ../config/.env
    environment:
      - EXCHANGE=${EXCHANGE:-gate}
      - CONTRACT_TYPE=${CONTRACT_TYPE:-USDT}
      - COIN_NAME=${COIN_NAME:-X}
      - GRID_SPACING=${GRID_SPACING:-0.004}
      - INITIAL_QUANTITY=${INITIAL_QUANTITY:-1}
      - LEVERAGE=${LEVERAGE:-20}
      - ENABLE_NOTIFICATIONS=${ENABLE_NOTIFICATIONS:-true}
      - NOTIFICATION_INTERVAL=${NOTIFICATION_INTERVAL:-3600}
      - GRID_MODE=${GRID_MODE:-single}
    
    # 挂载卷 - 持久化日志和配置
    volumes:
      - ../log:/app/log
      - ../config:/app/config:ro  # 只读配置目录
      - ../config/.env:/app/.env:ro  # 环境变量文件
      - ../config/symbols.yaml:/app/config/symbols.yaml:ro  # 多币种配置文件
      - ../config/symbols.json:/app/config/symbols.json:ro  # 多币种配置文件（可选）
      - ../src/multi_bot/state:/app/src/multi_bot/state  # 装死状态文件目录
    
    # 网络配置
    networks:
      - trader-network
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python", "/app/scripts/health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  trader-network:
    driver: bridge

volumes:
  log-data:
    driver: local 